name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: npm
    - name: Install Dependencies
      run: npm i
    - name: Download Library Files
      run: npm run fetch

    - name: Compile
      run: npm run compile
      env:
        NODE_OPTIONS: --max-old-space-size=4096
        TW_ENABLE_UPDATE_CHECKER: "1"

    - name: Package Windows
      if: runner.os == 'Windows'
      run: |
        npx electron-builder --windows nsis --x64 --publish always
        npx electron-builder --windows nsis --ia32 --publish always
        npx electron-builder --windows nsis --arm64 --publish always
        npx electron-builder --windows portable --x64 --publish always
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Package Microsoft Store
      # Microsoft Store artifact needs to completely recompile the JS since we don't want the update checker
      if: runner.os == 'Windows'
      run: npm run dist -- --windows appx --x64 --ia32 --arm64 --publish never
      env:
        NODE_OPTIONS: --max-old-space-size=4096
    - name: Upload Microsoft Store Artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: appx
        path: dist/*.appx

    - name: Package macOS
      if: runner.os == 'macOS'
      run: |
        npx electron-builder --mac dmg --universal --publish always
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLE_ID_USERNAME: ${{ secrets.APPLE_ID_USERNAME }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        CSC_LINK: ${{ secrets.CSC_LINK }}

    - name: Package Linux
      if: runner.os == 'Linux'
      run: |
        npx electron-builder --linux deb --x64 --publish always
        npx electron-builder --linux deb --arm64 --publish always
        npx electron-builder --linux deb --armv7l --publish always
        npx electron-builder --linux tar.gz --x64 --publish always
        npx electron-builder --linux tar.gz --arm64 --publish always
        npx electron-builder --linux tar.gz --armv7l --publish always
        npx electron-builder --linux AppImage --x64 --publish always
        npx electron-builder --linux AppImage --arm64 --publish always
        npx electron-builder --linux AppImage --armv7l --publish always
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
